title: Centre Qi Gong Hamburg
name: Urs Reupke
email: ursreupke@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Centre Qi Gong Hamburg. Entspannung und Bewegung. Kurse und Lehrerausbildung.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://centre-qigong-hamburg.de" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  urskr

remote_theme: "mmistakes/minimal-mistakes@4.27.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache

site-locale: de-DE
search: true
lunr:
  search_within_pages: true

include: ["_pages"]

footer:
  links:
    - label: "Impressum"
      icon: "fa-solid fa-file-contract"
      url: "/impressum"
    - label: "Datenschutz"
      icon: "fa-solid fa-shield"
      url: "/ds"

defaults:
  # _posts
  - 
    scope:
      path: ""
      type: posts
    values:
      layout: single
      author: "Urs"
      author_profile: true
      tagline: "" #else posts show their first line as tagline
      header:
        overlay_image: /assets/images/image.png
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author: "Urs"
      header:
        overlay_image: /assets/images/image.png

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
